version: '3.9'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html


#  web:
#    build:
#      context: .
#      dockerfile: ./app/Dockerfile
#    command: bash -c "python manage.py runserver 0.0.0.0:8000"
#    volumes:
#      - .:/code
#      - static_volume:/code/static
#    ports:
#      - "8000:8000"
#    depends_on:
#      db:
#        condition: service_healthy
#
#
#  db:
#    image: postgres:17.0
#    env_file:
#      - .env
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 10s
#      timeout: 10s
#      retries: 5
#    expose:
#      - "5432"
#
#
#networks:
#  default:
#
#volumes:
#  postgres_data:
#  static_volume: