version: '3.12'

services:
  web:
    build: .
    command:
      - python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_HOST=db
      - DEBUG=True
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:17.0
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5


networks:
  default:

volumes:
  postgres_data:
  static_volume: